import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Navbars from '@/components/Navbars'
import Footer from '@/components/Footer'
import ProductComponent from '@/components/ProductComponent'
import ProductDetail from '@/components/ProductDetail'
import ShoppingCard from '@/components/ShoppingCard'
import CategoriesNav from '@/components/CategoriesNav'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbars />
      <main className={styles.main}>
        <div className={styles.center}>
          <CategoriesNav />
        </div>
        <ProductComponent />
        <ShoppingCard />
      </main>
      <Footer />
    </>
  )
}
